### ISSUE TITLE
TTS: Documentation on voice configuration

### ISSUE THREAD

**Issue by HappyDOGE** [TinkoffCreditSystems/tinkoff-speech-api-examples#31]
I was unable to change the gender of the voice in both node.js and C# API examples.
Is there any documentation on available TTS voices and language codes?

**Comment by HappyDOGE** [comment]
Ok, I've found the supposed voice list
["alyona", "oleg", "maxim", "flirt"]
However "oleg" and "maxim" voices are the same.
Is this a bug or Oleg voice has been renamed?

**Comment by mykola-semenov** [comment]
Hello! Since different API keys have access to different sets of voices, we have implemented the ListVoices method.

The documentation can be found [here](https://voicekit.tinkoff.ru/docs/ttsgrpcapi/#tinkoff.cloud.tts.v1.TextToSpeech) and [here](https://github.com/TinkoffCreditSystems/voicekit-examples/blob/master/apis/tinkoff/cloud/tts/v1/tts.proto#L10). Useful code snippets can be found [here](https://github.com/TinkoffCreditSystems/voicekit-examples/blob/master/python/snippets/tts_list_voices.py) and [here](https://voicekit.tinkoff.ru/docs/ttstutorial/#method-list-voices).

Additionally, to access the up-to-date functionality, it is recommended to generate your own clients from the GRPC API and use them as described in [code snippets](https://github.com/TinkoffCreditSystems/voicekit-examples/blob/master/python/snippets).
