### ISSUE TITLE
warning: Import google

### ISSUE THREAD

**Issue by Smiley-k** [TinkoffCreditSystems/tinkoff-speech-api-examples#5]
Hey, what could be the problem?

./sh/generate_protobuf.sh
apis/tts.proto:5:1: warning: Import google/protobuf/duration.proto but not used.

**Comment by penguin138** [comment]
Hi. It is actually not a problem, it is a warning that tts.proto has an unused import. This warning is being produced by protoc, because if you look closely at the file python/apis/tts.proto, no protobuf messages from google/protobuf/duration.proto are used there. However, it does not mean that there is an error of some sort, the script is working correctly. I'll update tts.proto so this warning does not confuse anyone. Thanks for reporting this!

**Comment by penguin138** [comment]
Fixed it in 597d0c2e49f99931d97bdfb4f84a3e81b154c108
